server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;

    location = / {
        return 301 http://$host:8080/smarthome-escape/;
    }

    location /smarthome-escape/ {
        index index.html;
        try_files $uri $uri/ /smarthome-escape/index.html;
    }
}
