server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;

    location = / {
        return 301 http://$host:8090/smarthome-challenge/;
    }

    location /smarthome-challenge/ {
        index index.html;
        try_files $uri $uri/ /smarthome-challenge/index.html;
    }
}
