image: node:23.11.0

variables:
  DEV_BRANCH_NAME: "development"
  TEST_BRANCH_NAME: "main"
  SCHEDULE: "schedule"
  PIPELINE_BRANCH: "fix-simplify-pipeline"

stages:
  - schedule
  - lint
  - unitTest
  - build
  - integrationTest
  - systemTest
  - deploy

before_script:
  - npm install

start-server-job:
  stage: schedule
  rules:
    - if: '$CI_PIPELINE_SOURCE == $SCHEDULE'
  before_script:
    - apt update
    - apt install -y python3-dev pipx
    - pipx install python-openstackclient
    - export PATH=$PATH:/root/.local/bin
  script:
    - . pipeline/cd/IP34-25bb_SmartHomeEscape-openrc.sh
    - . pipeline/cd/server_running.sh

lint-job:
  stage: lint
  rules:
    - if: '$CI_PIPELINE_SOURCE != $SCHEDULE'
  script:
    - echo "[JOB] Linting"
    - npm run lint
  artifacts:
    paths:
      - lint/

test-job:
  stage: unitTest
  rules:
    - if: '$CI_PIPELINE_SOURCE != $SCHEDULE'
  before_script:
    - npm install save-dev jest
    - npm install save-dev ts-jest @types/jest typescript
  script:
    - echo "[JOB] Unit-tests"
    - npm test -- --passWithNoTests --testPathIgnorePatterns="IT"
  artifacts:
    paths:
      - coverage/unit/

build-job:
  stage: build
  rules:
    - if: '$CI_PIPELINE_SOURCE != $SCHEDULE'
  script:
    - echo "[JOB] Build"
    - npm run extract
    - npm run compile
    - npm run build
    - cp -r dist/ build/
    - mkdir config
    - cp pipeline/cd/nginxDevelopment.conf config/nginxDevelopment.conf
    - cp pipeline/cd/nginxTesting.conf config/nginxTesting.conf
  artifacts:
    paths:
      - build/
      - config/
  after_script:
    - ls -al

build-dev-container-job:
  stage: build
  tags:
    - dind
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  rules:
    - if: '$CI_PIPELINE_SOURCE != $SCHEDULE && $CI_COMMIT_BRANCH == $DEV_BRANCH_NAME'
  needs:
    - build-job
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build -f devEnvDockerfile --tag $CI_REGISTRY_IMAGE:dev_environment-latest .
    - docker build -f pipeline/cd/nginxDevDockerfile --tag $CI_REGISTRY_IMAGE:custom_nginx_dev-latest .
    - docker push $CI_REGISTRY_IMAGE:dev_environment-latest
    - docker push $CI_REGISTRY_IMAGE:custom_nginx_dev-latest

build-testing-container-job:
  stage: build
  tags:
    - dind
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  rules:
    - if: '$CI_PIPELINE_SOURCE != $SCHEDULE && $CI_COMMIT_BRANCH == $TEST_BRANCH_NAME'
  needs:
    - build-job
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build -f testingEnvDockerfile --tag $CI_REGISTRY_IMAGE:testing_environment-latest .
    - docker build -f pipeline/cd/nginxTestingDockerfile --tag $CI_REGISTRY_IMAGE:custom_nginx_testing-latest .
    - docker push $CI_REGISTRY_IMAGE:testing_environment-latest
    - docker push $CI_REGISTRY_IMAGE:custom_nginx_testing-latest


build-new-dev-container-job:
  stage: build
  rules:
    - if: '$CI_PIPELINE_SOURCE != $SCHEDULE && $CI_COMMIT_BRANCH == $PIPELINE_BRANCH'
  needs:
    - build-job
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin "$CI_REGISTRY"
  script:
    - docker build -f pipeline/cd/NEW_nginx_DEV_Dockerfile --tag $CI_REGISTRY_IMAGE:app_dev-latest .
    - docker push $CI_REGISTRY_IMAGE:app_dev-latest


build-new-prod-container-job:
  stage: build
  rules:
    - if: '$CI_PIPELINE_SOURCE != $SCHEDULE && $CI_COMMIT_BRANCH == $PIPELINE_BRANCH'
  needs:
    - build-job
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin "$CI_REGISTRY"
  script:
    - docker build -f pipeline/cd/NEW_nginx_PROD_Dockerfile --tag $CI_REGISTRY_IMAGE:app_prod-latest .
    - docker push $CI_REGISTRY_IMAGE:app_prod-latest





integrationTest-job:
  stage: integrationTest
  rules:
    - if: '$CI_PIPELINE_SOURCE != $SCHEDULE'
  before_script:
    - npm install save-dev jest
    - npm install save-dev ts-jest @types/jest typescript
  script:
    - echo "[JOB] Integration testing"
    - npm test -- --passWithNoTests --testPathPattern="IT"
  artifacts:
    paths:
      - coverage/IT/
  dependencies:
    - build-job

system-test-job:
  stage: systemTest
  rules:
    - if: '$CI_PIPELINE_SOURCE != $SCHEDULE && $CI_COMMIT_BRANCH == $TEST_BRANCH_NAME'
  before_script:
    - npm install save-dev jest
    - npm install save-dev ts-jest @types/jest typescript
  script:
    - echo "[JOB] System tests"
    - echo "[NOT IMPLEMENTED] System tests using Selenium"

deploy-dev:
  stage: deploy
  tags: [docker_runner]
  rules: [ { if: '$CI_COMMIT_BRANCH == $PIPELINE_BRANCH' } ]
  script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin "$CI_REGISTRY"
    - docker compose -f docker-compose.deploy.yml --profile dev pull
    - docker compose -f docker-compose.deploy.yml --profile dev up -d --remove-orphans

deploy-prod:
  stage: deploy
  tags: [docker_runner]
  rules: [ { if: '$CI_COMMIT_BRANCH == $PIPELINE_BRANCH' } ]
  script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin "$CI_REGISTRY"
    - docker compose -f docker-compose.deploy.yml --profile prod pull
    - docker compose -f docker-compose.deploy.yml --profile prod up -d --remove-orphans

