image: node:20-alpine

variables:
  DEV_BRANCH_NAME: "development"
  TEST_BRANCH_NAME: "main"
  SCHEDULE: "schedule"

stages:
  - schedule
  - lint
  - unitTest
  - build
  - integrationTest
  - systemTest
  - deploy

before_script:
  - npm install
  - npx patch-package

start-server-job:
  stage: schedule
  rules:
    - if: '$CI_PIPELINE_SOURCE == $SCHEDULE'
  before_script:
    - apt update
    - apt install -y python3-dev pipx
    - pipx install python-openstackclient
    - export PATH=$PATH:/root/.local/bin
  script:
    - . pipeline/cd/IP34-25bb_SmartHomeEscape-openrc.sh
    - . pipeline/cd/server_running.sh  

lint-job:
  stage: lint
  rules:
    - if: '$CI_PIPELINE_SOURCE != $SCHEDULE'
  script:
    - echo "[JOB] Linting"
    - npm run lint
  artifacts:
    paths:
      - lint/

test-job:
  stage: unitTest
  rules:
    - if: '$CI_PIPELINE_SOURCE != $SCHEDULE'
  before_script:
    - npm install save-dev jest
    - npm install save-dev ts-jest @types/jest typescript
  script:
    - echo "[JOB] Unit-tests"
    - npm test -- --passWithNoTests --testPathIgnorePatterns="IT"
  artifacts:
    paths:
      - coverage/unit/

build-job:
  stage: build
  rules:
    - if: '$CI_PIPELINE_SOURCE != $SCHEDULE'
  script:
    - echo "[JOB] Build"
    - npm run extract
    - npm run compile
    - npm run build
    - cp -r dist/ build/
    - mkdir config
    - cp pipeline/cd/nginxDevelopment.conf config/nginxDevelopment.conf
    - cp pipeline/cd/nginxTesting.conf config/nginxTesting.conf
  artifacts:
    paths:
      - build/
      - config/
  after_script:
    - ls -al

build-dev-container-job:
  stage: build
  tags:
    - dind
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  rules:
    - if: '$CI_PIPELINE_SOURCE != $SCHEDULE && $CI_COMMIT_BRANCH == $DEV_BRANCH_NAME'
  needs:
    - build-job
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build -f devEnvDockerfile --tag $CI_REGISTRY_IMAGE:dev_environment-latest .
    - docker build -f pipeline/cd/nginxDevDockerfile --tag $CI_REGISTRY_IMAGE:custom_nginx_dev-latest .
    - docker push $CI_REGISTRY_IMAGE:dev_environment-latest
    - docker push $CI_REGISTRY_IMAGE:custom_nginx_dev-latest

build-testing-container-job:
  stage: build
  tags:
    - dind
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  rules:
    - if: '$CI_PIPELINE_SOURCE != $SCHEDULE && $CI_COMMIT_BRANCH == $TEST_BRANCH_NAME'
  needs:
    - build-job
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build -f testingEnvDockerfile --tag $CI_REGISTRY_IMAGE:testing_environment-latest .
    - docker build -f pipeline/cd/nginxTestingDockerfile --tag $CI_REGISTRY_IMAGE:custom_nginx_testing-latest .
    - docker push $CI_REGISTRY_IMAGE:testing_environment-latest
    - docker push $CI_REGISTRY_IMAGE:custom_nginx_testing-latest

integrationTest-job:
  stage: integrationTest
  rules:
    - if: '$CI_PIPELINE_SOURCE != $SCHEDULE'
  before_script:
    - npm install save-dev jest
    - npm install save-dev ts-jest @types/jest typescript
  script:
    - echo "[JOB] Integration testing"
    - npm test -- --passWithNoTests --testPathPattern="IT"
  artifacts:
    paths:
      - coverage/IT/
  dependencies:
    - build-job

system-test-job:
  stage: systemTest
  rules:
    - if: '$CI_PIPELINE_SOURCE != $SCHEDULE && $CI_COMMIT_BRANCH == $TEST_BRANCH_NAME'
  before_script:
    - npm install save-dev jest
    - npm install save-dev ts-jest @types/jest typescript
  script:
    - echo "[JOB] System tests"
    - echo "[NOT IMPLEMENTED] System tests using Selenium"


deploy-test-job:
  stage: deploy
  image: alpine:3.20
  environment:
    name: testing
  rules:
    - if: '$CI_PIPELINE_SOURCE != $SCHEDULE && $CI_COMMIT_BRANCH == $TEST_BRANCH_NAME'
  dependencies:
    - build-testing-container-job
    - system-test-job
  services:
    - docker:dind
  before_script:
    - apk add openssh-client
  script:
    - echo "[JOB] Deploy"
    - eval `ssh-agent`
    - echo "$SSH_PK_DEVELOPMENT" | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - touch ~/.ssh/known_hosts
    - chmod 600 ~/.ssh/known_hosts
    - echo $SSH_HOST_KEY >> ~/.ssh/known_hosts
    - |
      ssh development@86.119.46.247 \
      "export TESTING_IMAGE='$CI_REGISTRY_IMAGE:testing_environment-latest'; \
      export TESTING_NGINX_IMAGE='$CI_REGISTRY_IMAGE:custom_nginx_testing-latest'; \
      export CI_REGISTRY='$CI_REGISTRY'; \
      export CI_REGISTRY_USER='$CI_REGISTRY_USER'; \
      export CI_REGISTRY_PASSWORD='$CI_REGISTRY_PASSWORD'; \
      bash -s" << 'SSH_COMMAND' 
        cd /home/development
      
        echo "$CI_REGISTRY_PASSWORD" | docker login --username "$CI_REGISTRY_USER" --password-stdin "$CI_REGISTRY"
        docker pull "$TESTING_IMAGE"
        docker pull "$TESTING_NGINX_IMAGE"
      
        TEST_CONTAINER_RUNNING=`docker ps -q -f name=test_container`
        TEST_CONTAINER_EXISTING=`docker ps -qa -f name=test_container`
      
        if [ "$TEST_CONTAINER_RUNNING" ]; then
            echo "[INFO] test_container is already running. Skipping creation."
        elif [ "$TEST_CONTAINER_EXISTING" ]; then
            echo "[INFO] test_container exists but is not running. Starting it..."
            docker start test_container
        else
            echo "[INFO] test_container is not running. Creating it..."
            docker ps -a
            docker run -d --privileged -p 8080:8080 --name test_container "$TESTING_IMAGE"
            sleep 5
        fi
      
        docker exec \
        -e TESTING_NGINX_IMAGE="$TESTING_NGINX_IMAGE" \
        -e CI_REGISTRY_PASSWORD="$CI_REGISTRY_PASSWORD" \
        -e CI_REGISTRY="$CI_REGISTRY" \
        -e CI_REGISTRY_USER="$CI_REGISTRY_USER" \
        test_container sh -c '
          cd /home/deploy &&
        
          WEBSERVER_CONTAINER_RUNNING=`docker ps -q -f name=webserver`
          WEBSERVER_CONTAINER_EXISTING=`docker ps -qa -f name=webserver`
          
          if [ "$WEBSERVER_CONTAINER_RUNNING" ]; then
            echo "[INFO] Webserver is already running. Restarting..."
          elif [ "$WEBSERVER_CONTAINER_EXISTING" ]; then
            echo "[INFO] Webserver stopped. Removing old one..."
          else
            echo "[INFO] Webserver not existing. Creating new one..."
          fi
          
          echo "$CI_REGISTRY_PASSWORD" | docker login --username "$CI_REGISTRY_USER" --password-stdin "$CI_REGISTRY"
          docker rm -f webserver 2>/dev/null || true
          docker pull "$TESTING_NGINX_IMAGE"
          docker run -d --privileged -p 8080:80 --name webserver "$TESTING_NGINX_IMAGE"
        '
      SSH_COMMAND


deploy-dev-job:
  stage: deploy
  image: alpine:3.20
  environment:
    name: development
  rules:
    - if: '$CI_PIPELINE_SOURCE != $SCHEDULE && $CI_COMMIT_BRANCH == $DEV_BRANCH_NAME'
  dependencies:
    - build-testing-container-job
    - start-server-job
  services:
    - docker:dind
  before_script:
    - apk add openssh-client
  script:
    - echo "[JOB] Deploy"
    - eval `ssh-agent`
    - echo "$SSH_PK_DEVELOPMENT" | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - touch ~/.ssh/known_hosts
    - chmod 600 ~/.ssh/known_hosts
    - echo $SSH_HOST_KEY >> ~/.ssh/known_hosts
    - |
      ssh development@86.119.46.247 \
      "export DEV_IMAGE='$CI_REGISTRY_IMAGE:dev_environment-latest'; \
      export DEV_NGINX_IMAGE='$CI_REGISTRY_IMAGE:custom_nginx_dev-latest'; \
      export CI_REGISTRY='$CI_REGISTRY'; \
      export CI_REGISTRY_USER='$CI_REGISTRY_USER'; \
      export CI_REGISTRY_PASSWORD='$CI_REGISTRY_PASSWORD'; \
      bash -s" << 'SSH_COMMAND' 
        cd /home/development
      
        echo "$CI_REGISTRY_PASSWORD" | docker login --username "$CI_REGISTRY_USER" --password-stdin "$CI_REGISTRY"
        docker pull "$DEV_IMAGE"
            
        DEV_CONTAINER_RUNNING=`docker ps -q -f name=dev_container`
        DEV_CONTAINER_EXISTING=`docker ps -qa -f name=dev_container`
        
        if [ "$DEV_CONTAINER_RUNNING" ]; then
            echo "[INFO] dev_container is already running. Skipping creation."
        elif [ "$DEV_CONTAINER_EXISTING" ]; then
            echo "[INFO] dev_container exists but is not running. Starting it..."
            docker start dev_container
        else
            echo "[INFO] dev_container is not running. Creating it..."
            docker run -d --privileged -p 8090:8090 --name dev_container "$DEV_IMAGE"
            sleep 5
        fi
        
        docker exec \
        -e DEV_NGINX_IMAGE="$DEV_NGINX_IMAGE" \
        -e CI_REGISTRY_PASSWORD="$CI_REGISTRY_PASSWORD" \
        -e CI_REGISTRY="$CI_REGISTRY" \
        -e CI_REGISTRY_USER="$CI_REGISTRY_USER" \
        dev_container sh -c '
          cd /home/deploy &&
      
          WEBSERVER_CONTAINER_RUNNING=`docker ps -q -f name=webserver`
          WEBSERVER_CONTAINER_EXISTING=`docker ps -qa -f name=webserver`
      
          if [ "$WEBSERVER_CONTAINER_RUNNING" ]; then
            echo "[INFO] Webserver is already running. Restarting..."
          elif [ "$WEBSERVER_CONTAINER_EXISTING" ]; then
            echo "[INFO] Webserver stopped. Removing old one..."
          else
            echo "[INFO] Webserver not existing. Creating new one..."
          fi
          
          echo "$CI_REGISTRY_PASSWORD" | docker login --username "$CI_REGISTRY_USER" --password-stdin "$CI_REGISTRY"
          docker rm -f webserver 2>/dev/null || true
          docker pull "$DEV_NGINX_IMAGE"
          docker run -d --privileged -p 8090:80 --name webserver "$DEV_NGINX_IMAGE"
        '
      SSH_COMMAND

