image: node:20-alpine

variables:
  DEV_BRANCH_NAME: "development"
  PROD_BRANCH_NAME: "main"
  SCHEDULE: "schedule"
  SERVER_IP: 86.119.46.247

stages:
  - schedule
  - lint
  - unitTest
  - build
  - integrationTest
  - systemTest
  - deploy

before_script:
  - npm install
  - npx patch-package

start-server-job:
  stage: schedule
  rules:
    - if: '$CI_PIPELINE_SOURCE == $SCHEDULE'
  before_script:
    - apk update
    - apk add --no-cache build-base python3-dev pipx linux-headers
    - pipx install python-openstackclient
    - export PATH=$PATH:/root/.local/bin
  script:
    - . pipeline/cd/IP34-25bb_SmartHomeEscape-openrc.sh
    - . pipeline/cd/server_running.sh

lint-job:
  stage: lint
  rules:
    - if: '$CI_PIPELINE_SOURCE != $SCHEDULE'
  before_script:
    - npm install
  script:
    - echo "[JOB] Linting"
    - npm run lint
  artifacts:
    paths:
      - lint/

test-job:
  stage: unitTest
  rules:
    - if: '$CI_PIPELINE_SOURCE != $SCHEDULE'
  before_script:
    - npm install
    - npm install --save-dev jest
    - npm install --save-dev ts-jest @types/jest typescript
  script:
    - echo "[JOB] Unit-tests"
    - npm test -- --passWithNoTests --testPathIgnorePatterns="IT"
  artifacts:
    paths:
      - coverage/unit/

build-job:
  stage: build
#  rules:
#    - if: '$CI_PIPELINE_SOURCE != $SCHEDULE'
  before_script:
    - npm install
  script:
    - echo "[JOB] Build"
    - npm run build
    - cp -r dist/ build/
    - mkdir config
    - cp pipeline/cd/nginxDevelopment.conf config/nginxDevelopment.conf
    - cp pipeline/cd/nginxProd.conf config/nginxProd.conf
  artifacts:
    paths:
      - build/
      - config/


build-dev-container-job:
  stage: build
  image: docker:29-cli
  tags: [docker_runner]
#  rules:
#    - if: '$CI_PIPELINE_SOURCE != $SCHEDULE && $CI_COMMIT_BRANCH == $DEV_BRANCH_NAME'
  needs:
    - build-job
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin "$CI_REGISTRY"
  script:
    - docker build -f pipeline/cd/Dockerfile_dev --tag $CI_REGISTRY_IMAGE:app_dev-latest .
    - docker push $CI_REGISTRY_IMAGE:app_dev-latest


build-prod-container-job:
  stage: build
  image: docker:29-cli
  tags: [docker_runner]
  rules:
    - if: '$CI_PIPELINE_SOURCE != $SCHEDULE && $CI_COMMIT_BRANCH == $PROD_BRANCH_NAME'
  needs:
    - build-job
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin "$CI_REGISTRY"
  script:
    - docker build -f pipeline/cd/Dockerfile_prod --tag $CI_REGISTRY_IMAGE:app_prod-latest .
    - docker push $CI_REGISTRY_IMAGE:app_prod-latest


integrationTest-job:
  stage: integrationTest
  rules:
    - if: '$CI_PIPELINE_SOURCE != $SCHEDULE'
  before_script:
    - npm install
    - npm install --save-dev jest
    - npm install --save-dev ts-jest @types/jest typescript
  script:
    - echo "[JOB] Integration testing"
    - npm test -- --passWithNoTests --testPathPattern="IT"
  artifacts:
    paths:
      - coverage/IT/
  dependencies:
    - build-job

system-test-job:
  stage: systemTest
  rules:
    - if: '$CI_PIPELINE_SOURCE != $SCHEDULE && $CI_COMMIT_BRANCH == $PROD_BRANCH_NAME'
  before_script:
    - npm install --save-dev jest
    - npm install --save-dev ts-jest @types/jest typescript
  script:
    - echo "[JOB] System tests"
    - echo "[NOT IMPLEMENTED] System tests using Selenium"

deploy-dev:
  stage: deploy
  image: docker:29-cli
  tags: [docker_runner]
  before_script: []
#  rules:
#    - if: '$CI_PIPELINE_SOURCE != $SCHEDULE && $CI_COMMIT_BRANCH == $DEV_BRANCH_NAME'
  script:
    # Setup ssh
    - apk add --no-cache openssh-client
    - eval `ssh-agent`
    - echo "$SSH_PK_DEVELOPMENT" | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - touch ~/.ssh/known_hosts
    - chmod 600 ~/.ssh/known_hosts
    - echo $SSH_HOST_KEY >> ~/.ssh/known_hosts
    # Copy docker compose and start on host via ssh
    - scp docker-compose.deploy.yml development@$SERVER_IP:/app/docker-compose.deploy.yml
    - ssh development@$SERVER_IP "cd /app && 
      CI_REGISTRY_IMAGE='$CI_REGISTRY_IMAGE' && CI_REGISTRY_USER='$CI_REGISTRY_USER' && CI_REGISTRY='$CI_REGISTRY' && CI_REGISTRY_PASSWORD='$CI_REGISTRY_PASSWORD' 
      echo '$CI_REGISTRY_PASSWORD' | docker login --username '$CI_REGISTRY_USER' --password-stdin '$CI_REGISTRY' 
      docker compose -f docker-compose.deploy.yml --profile dev up -d --remove-orphans"

deploy-prod:
  stage: deploy
  image: docker:29-cli
  tags: [docker_runner]
  rules:
    - if: '$CI_PIPELINE_SOURCE != $SCHEDULE && $CI_COMMIT_BRANCH == $PROD_BRANCH_NAME'
  script:
    - apk add --no-cache openssh-client
    - scp docker-compose.deploy.yml development@$SERVER_IP:/app/docker-compose.deploy.yml
    - ssh development@$SERVER_IP \
      "cd /app && CI_REGISTRY_IMAGE=$CI_REGISTRY_IMAGE docker compose -f docker-compose.deploy.yml --profile prod up -d --remove-orphans"

