import { //import icons you need here
  Fingerprint,
  TestTubeDiagonal,
  Dna,
  SmilePlus,
  Speech,
  Handshake,
  MapPinHouse,
  LandPlot,
  Mail,
  BookUser,
  Cake,
  CreditCard,
  MapPinned,
  Radar,
  Tickets,
  SquareChartGantt,
  Megaphone,
  CloudRainWind,
  TextSearch,
  Map,
} from "lucide-react";

export const Icons = {
  fingerprint: Fingerprint,
  bltest: TestTubeDiagonal,
  dna: Dna,
  belief:SmilePlus,
  speech: Speech,
  hand: Handshake,
  house: MapPinHouse,
  adr: LandPlot,
  mail: Mail,
  nmbr: BookUser,
  birth: Cake,
  card: CreditCard,
  ip: MapPinned,
  gps: Radar,
  event: Tickets,
  announ: Megaphone,
  bus: SquareChartGantt,
  rain: CloudRainWind,
  data: TextSearch,
  map: Map,
}